USE [master]
GO
/****** Object:  Database [Api_Groceries]    Script Date: 30/12/2020 3:41:01 μμ ******/
CREATE DATABASE [Api_Groceries]
CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'test', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\test.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
LOG ON
( NAME = N'test_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\test_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Api_Groceries] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Api_Groceries].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Api_Groceries] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Api_Groceries] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Api_Groceries] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Api_Groceries] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Api_Groceries] SET ARITHABORT OFF
GO
ALTER DATABASE [Api_Groceries] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Api_Groceries] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Api_Groceries] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Api_Groceries] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Api_Groceries] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Api_Groceries] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Api_Groceries] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Api_Groceries] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Api_Groceries] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Api_Groceries] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Api_Groceries] SET  DISABLE_BROKER
GO
ALTER DATABASE [Api_Groceries] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Api_Groceries] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Api_Groceries] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Api_Groceries] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Api_Groceries] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Api_Groceries] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Api_Groceries] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Api_Groceries] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Api_Groceries] SET  MULTI_USER
GO
ALTER DATABASE [Api_Groceries] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Api_Groceries] SET DB_CHAINING OFF
GO
ALTER DATABASE [Api_Groceries] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [Api_Groceries] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO
USE [Api_Groceries]
GO
/****** Object:  Table [dbo].[Mappings]    Script Date: 30/12/2020 3:41:01 μμ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Mappings](
[sCode] [varchar](255) NOT NULL,
[pName] [varchar](255) NOT NULL,
CONSTRAINT [PK_Mappings_1] PRIMARY KEY CLUSTERED
(
[pName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Records]    Script Date: 30/12/2020 3:41:01 μμ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Records](
[price] [float] NOT NULL,
[name] [varchar](255) NOT NULL,
[pDate] [datetime] NOT NULL,
[origin] [varchar](50) NOT NULL,
[number] [varchar](50) NOT NULL,
[quantity] [float] NOT NULL,
[discount] [float] NOT NULL,
[tax] [float] NOT NULL,
[measurement_unit] [varchar](50) NOT NULL,
[newPrice] [float] NULL,
[sCode] [varchar](255) NOT NULL,
CONSTRAINT [PK_Invoices] PRIMARY KEY CLUSTERED
(
[name] ASC,
[pDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Rules]    Script Date: 30/12/2020 3:41:01 μμ ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Rules](
[sCode] [varchar](255) NOT NULL,
[profitPercentage] [float] NOT NULL,
[minProfit] [float] NOT NULL,
CONSTRAINT [PK_Rules] PRIMARY KEY CLUSTERED
(
[sCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Mappings]  WITH CHECK ADD  CONSTRAINT [FK_Mappings_Rules] FOREIGN KEY([sCode])
REFERENCES [dbo].[Rules] ([sCode])
GO
ALTER TABLE [dbo].[Mappings] CHECK CONSTRAINT [FK_Mappings_Rules]
GO
USE [master]
GO
ALTER DATABASE [Api_Groceries] SET  READ_WRITE
GO
